apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodeport }}
{{- end }}
  selector:
    app: grafana
  type: {{ .Values.service.type }}
