apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-rules
  namespace: {{ .Values.global.namespace }}
data:
  podmemory.rules: |
    groups:
    - name: prometheus alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 5s
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  memory.rules: |
    groups:
    - name: NodeAlerts
      rules:
      - alert: NodeCPUUsage
        expr: (100 - (avg(irate(node_cpu{mode="idle"}[5m])) BY (instance) * 100)) > 75
        for: 2m
        labels:
          severity: slack
        annotations:
          description: '{{$labels.instance}}: CPU usage is above 75% (current value is:
            {{ $value }})'
          summary: '{{$labels.instance}}: High CPU usage detect